### ISSUE TITLE
Support for other Secrets type

### ISSUE THREAD

**Issue by jfcoz** [enix/x509-certificate-exporter#12]
Please add support for other types of certificates : 
- `type: istio.io/ca-root`
- `type: istio.io/key-and-cert`

**Comment by arcln** [comment]
We added support for custom secret types in v2.7.0 / chart v1.9.0. It should solve your problem.

You can use it like so:

```yaml
# values.yaml

secretsExporter:
  secretTypes:
     - type: kubernetes.io/tls
       key: tls.crt
     - type: istio.io/key-and-cert
       key: cert-chain.pem
     - type: istio.io/key-and-cert
       key: root-cert.pem
     - ...
```
