### ISSUE TITLE
Prometheus and x509.yml files

### ISSUE THREAD

**Issue by vasile890** [enix/x509-certificate-exporter#134]
Hi team,

Could you please advise about the Prometheus configuration in order to use it with Prometheus and Grafana.
I am looking for something like this:

```yml
prometheus.yml
  # Example job [icmp] module
  - job_name: 'x509'
    static_configs:
      - targets:  ['ip2', 'ip1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # Blackbox exporter Host:Port
        replacement: localhost:9115

```

```yml
x509.yml
modules:
  x509:
    prober: http
```

Could you please provide these kind of configuration files? I plan to use it standalone not with K8s or Helm.

Cheers!

**Comment by npdgm** [comment]
Hi,

It seems you try to use blackbox_exporter to fetch metrics from x509-certificate-exporter. You do not need blackbox_exporter and that `x509.yml` file to use this project.

Please note x509-certificate-exporter only works on certificate _files_ and will not query live servers to check certificates sent by TLS protocol.
If you want to watch certificates in server replies, then you only need blackbox_exporter and it's metric `probe_ssl_earliest_cert_expiry`.

This is a basic Prometheus scrape configuration that should work:
```yaml
scrape_configs:
  - job_name: x509-certificate-exporter
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
        - "ip1:9793"
        - "ip2:9793"
```

Cheers
