### ISSUE TITLE
Failure to parse k3s kubeconfig

### ISSUE THREAD

**Issue by dajudge** [enix/x509-certificate-exporter#142]
I am getting this error when running the hostPath DS on a k3s CP node:

```
time="2023-05-06T13:10:06Z" level=warning msg="failed to parse \"/mnt/watch/kube-ba6ba6fe109fb10a7bd584dc784d613c62acc220/etc/rancher/k3s/k3s.yaml\", failed to parse some labels in /mnt/watch/kube-ba6ba6fe109fb10a7bd584dc784d613c62acc220/etc/rancher/k3s/k3s.yaml (got 1 IDs but 2 certs for \"$.users[:].name\")"
```

The kubeconfig at first glance seems to look OK to me:
```
# cat /etc/rancher/k3s/k3s.yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <<CA DATA>>
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: <<CERT DATA>>
    client-key-data: <<KEY DATA>>
```
Is this maybe a misconfiguration or should this work as configured?

### Discussed in https://github.com/enix/x509-certificate-exporter/discussions/137
