### ISSUE TITLE
Daemonset for CP has no pods

### ISSUE THREAD

**Issue by lappehan** [enix/x509-certificate-exporter#154]
Hello,

Reinitialized my cluster but got an issue where exporters on masters are not being created
Got any ideas? Previsouly it was working 3-4 months ago, labels on cp and nodes are set, correct

Current helm values:
```yaml
secretsExporter:
  podAnnotations:
    prometheus.io/port: "9793"
    prometheus.io/scrape: "true"
service:
  create: false
prometheusServiceMonitor:
  create: false
prometheusRules:
  create: false

hostPathsExporter:
  podAnnotations:
    prometheus.io/port: "9793"
    prometheus.io/scrape: "true"

  daemonSets:
    cp:
      nodeSelector:
        certCheckMaster: x509Master
      tolerations:
      - effect: NoSchedule
        key: x509Master
        operator: Exists
      watchDirectories:
      - /etc/ssl/etcd/ssl 
      watchFiles:
      - /etc/kubernetes/ssl/apiserver.crt
      - /etc/kubernetes/ssl/front-proxy-ca.crt
      - /etc/kubernetes/ssl/front-proxy-client.crt
      - /etc/kubernetes/ssl/apiserver-kubelet-client.crt
      - /etc/kubernetes/ssl/ca.crt
      - /var/lib/kubelet/pki/kubelet.crt
      - /etc/kubernetes/pki/ca.crt
      watchKubeconfFiles:
      - /etc/kubernetes/admin.conf
      - /etc/kubernetes/controller-manager.conf
      - /etc/kubernetes/scheduler.conf

    nodes:
      nodeSelector:
        certCheck: x509
      tolerations:
      - effect: NoSchedule
        key: x509
        operator: Exists
      watchFiles:
      - /var/lib/kubelet/pki/kubelet-client-current.pem
      - /etc/kubernetes/pki/ca.crt
```
