### ISSUE TITLE
Feature request: Include a label with host/nodename for Helm installs when using Podannotations

### ISSUE THREAD

**Issue by davidusken** [enix/x509-certificate-exporter#159]
Would it be possible to include another label with the host/nodename when deploying with Helm? This would be a huge improvement for anyone running multiple single-node clusters. 

Currently we are able to distinguish between the different clusters using `app_kubernetes_io_instance` but this also includes namespace and name of the deployment in our case. 

Current values.yaml for reference:
```
prometheusServiceMonitor:
  create: false
prometheusRules:
  create: false
service:
  create: false
secretsExporter:
  podAnnotations:
    prometheus.io/port: "9793"
    prometheus.io/scrape: "true"

hostPathsExporter:
  podAnnotations:
    prometheus.io/port: "9793"
    prometheus.io/scrape: "true"
  daemonSets:
    nodes:
      watchDirectories:
      - /var/lib/rancher/k3s/server/tls
      - /var/lib/rancher/k3s/server/tls/etcd
```
