### ISSUE TITLE
Feature: Regex support in --secret-type flag

### ISSUE THREAD

**Issue by AnuragEkkati** [enix/x509-certificate-exporter#242]
New Feature Request:

We use x509 extensively in our production to monitor the certs. Recently during onboarding one of our internal customer, we realized that it is a hassle to keep adding the flag --secret-type for every custom key of the secret where the value is certificate we want to monitor. 

It will be very helpful if we have regex support like below 

`--secret-type=Opaque:.*.crt --secret-type=Opaque:.*.pem`

If x509 exporter has to scan all of the cluster secrets and if we have too many customizations in the secret keys it becomes unmanageable

**Comment by AnuragEkkati** [comment]
https://github.com/enix/x509-certificate-exporter/pull/243

**Comment by npdgm** [comment]
In v4 this was improved significantly. The `key:` field has a companion `keyPatterns:` that accepts a list of regular expressions, so any number of keys in the same Secret type can be matched at once.

```yaml
secretsExporter:
  secretTypes:
    # Standard TLS secrets
    - type: kubernetes.io/tls
      key: tls.crt

    # All keys ending in `.crt` inside an Opaque secret
    - type: Opaque
      keyPatterns:
        - '^.*\.crt$'
```

With a Secret like:
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bundle
  namespace: app
data:
  kafka.crt: ...
  user.crt: ...
  ca.crt: ...
  notes.txt: ...
```

You'll get three series, one per matched key:
```
x509_cert_not_after{secret_namespace="app", secret_name="bundle", secret_key="kafka.crt", subject_CN="..."}
x509_cert_not_after{secret_namespace="app", secret_name="bundle", secret_key="user.crt", subject_CN="..."}
x509_cert_not_after{secret_namespace="app", secret_name="bundle", secret_key="ca.crt", subject_CN="..."}
```
