### ISSUE TITLE
[feature request]Handel duplicate cert

### ISSUE THREAD

**Issue by muzammilrehman** [enix/x509-certificate-exporter#244]
With version 3.x.x, the server doesn't crash when Kubernetes secret has a duplicate certificate but it does not expose other certs' metrics. It would be good to either directly ignore the duplicate certs or give the option to the user via a flag to ignore these. 

```
~ # curl http://172.20.72.13:9793/metrics
An error has occurred while serving metrics:

collected metric "x509_cert_error" { label:{name:"secret_key"  value:"pubkey"}  label:{name:"secret_name"  value:"certs-server"}  label:{name:"secret_namespace"  value:"xxx"}  xxx:{value:1}} was collected before with the same name and label values
```

**Comment by AnuragEkkati** [comment]
@muzammilrehman this should be bug if it is 100% reproducible

**Comment by carinadigital** [comment]
I've encountered the same problem. I would suggest that if a duplicate cert is found then it's simply ignored and an error printed to the logs.

**Comment by eric-engberg** [comment]
I'm getting this same error on 3.18.1.  I don't see a duplicate cert in the cluster? Clearly I'm misunderstanding something.  What exactly is causing this? how is it possible to have a duplicate?

**Comment by npdgm** [comment]
Sorry for the silence on this issue. Truth be told, the codebase was hard to maintain and prone to regressions, and we lacked the test coverage needed to work on the project with confidence. This contributed to the lack of development. A new version was released last week with a complete architecture overhaul, new features, and solid test suites. Which now puts us in a better position to iterate on feature requests.

Regarding the issue you reported, in v4 this no longer happens. Duplicate certificates inside the same Secret (or the same PEM bundle) are handled automatically and `/metrics` keeps serving 200.

Two new mechanisms:

1. Collision discriminator label. When the exporter would emit two series with identical labels (your case: same `subject_CN`, same `secret_key`, etc.), it appends a `discriminator` label populated with a short SHA-256 prefix of the raw certificate bytes. The two duplicate certs end up as two distinct series instead of crashing the collector.

2. `x509_cert_collision_total` counter. Each resolved collision is counted, so you can alert on it and find out *which* Secrets contain duplicates. If you want to clean them up.

The default config enables the discriminator automatically when needed.

If you want to *force* a discriminator slot on every series (predictable label cardinality even when no collision occurs), or conversely opt out entirely (drop duplicates silently instead of disambiguating), the mode is configurable:

```yaml
metrics:
  # auto    — default: discriminator label appears only on colliding
  #           series; non-colliding ones keep the clean label set.
  # always  — discriminator label is always present; predictable
  #           cardinality for Prometheus rules and Grafana panels.
  # never   — no discriminator; the second of two colliding certs is
  #           dropped (you'll see x509_cert_collision_total tick up
  #           but only one of the two is observable).
  collisionDiscriminator: auto
```

Sample output with `auto` mode and two duplicate certs in a single Secret:

```
x509_cert_not_after{secret_namespace="app", secret_name="bundle", secret_key="tls.crt", subject_CN="cn.example", discriminator="a1b2c3d4"} 1.7234e+09
x509_cert_not_after{secret_namespace="app", secret_name="bundle", secret_key="tls.crt", subject_CN="cn.example", discriminator="e5f6a7b8"} 1.7234e+09

x509_cert_collision_total{...} 1
```

A worked example and the per-cert label schema are documented at [`docs/metrics.md`](https://github.com/enix/x509-certificate-exporter/blob/main/docs/metrics.md#x509_cert_collision_total).

Thanks for bringin up this issue.
