### ISSUE TITLE
Configmap check is enabled by default

### ISSUE THREAD

**Issue by fallen-up** [enix/x509-certificate-exporter#368]
in the latest version 3.18.0 there is an error.
secretsExporter.configMapKeys is not announced, this option is not thrown in deployment and clusterrole.
nevertheless, there is an error in the logs:
```
time=2024-12-25T15:32:22.470Z level=WARN msg="failed to fetch configmaps from namespace \"xxx\": configmaps is forbidden: User \"system:serviceaccount:kube-monitoring:x509-certificate-exporter\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"xxx\""
time=2024-12-25T15:32:22.470Z level=INFO msg="Discovered and parsed certificates" certificates=0 failures=1
```
it looks like the configmap check is enabled by default.

**Comment by nikatar** [comment]
I have this problem too

**Comment by npdgm** [comment]
Hi,
Thanks for reporting this issue. You are correct the implementation is flawed.
I'm adding a flag to enable fetching ConfigMaps and granting the ClusterRole only when needed.

**Comment by nikatar** [comment]
The problem is that if you don't enable configmap watching, secret watching doesn't work.
And the exporter started working correctly only after I set `secretsExporter.configMapKeys` in values. Although I don't have tls certificates in the configMaps

```yaml
    prometheusRules:
      create: false
    secretsExporter:
      configMapKeys: ["tls.crt"]
      includeNamespaces:
        - istio-system
 ```
