### ISSUE TITLE
can i use *.crt in secretTypes (wildcard)

### ISSUE THREAD

**Issue by SergeiCherevko** [enix/x509-certificate-exporter#376]
Hello! I have many secrets in my cluster. Some of them are named like "tls.crt," which is fine, but others are named like:
```
kafka.crt
user.crt
ca.crt
```
I don’t want to list all the names manually; instead, I want to use a wildcard to retrieve all of them. Can i make this like code below
```
secretsExporter:
  secretTypes:
  - type: kubernetes.io/tls
     key: tls.crt
  - type: opaque
     key: *.crt       <---------------------
```

**Comment by npdgm** [comment]
Hi!
We have never used the feature ourselves, but field `key:` has support for regexp patterns. So I would expect `key: '.*\.crt'` to work. The exporter won't start if the pattern doesn't compile.
I did a quick test and could not get it to work with your use-case... at least through the Helm chart, so perhaps we have templating issues.
Tomorrow I'll hunt for the bug

**Comment by SergeiCherevko** [comment]
Any updates?

**Comment by sopliakk** [comment]
+1
Problem not solved

**Comment by npdgm** [comment]
Sorry for the silence on this issue. Truth be told, the codebase was hard to maintain and prone to regressions, and we lacked the test coverage needed to work on the project with confidence. This contributed to the lack of development. A new version was released last week with a complete architecture overhaul, new features, and solid test suites. Which now puts us in a better position to iterate on feature requests.

 In v4 this is now possible. The `key:` field has a companion `keyPatterns:` that accepts a list of regular expressions, so any number of keys in the same Secret type can be matched at once.

For your case:

```yaml
secretsExporter:
  secretTypes:
    # Standard TLS secrets
    - type: kubernetes.io/tls
      key: tls.crt

    # All keys ending in `.crt` inside an Opaque secret
    - type: Opaque
      keyPatterns:
        - '^.*\.crt$'
```

With a Secret like:
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bundle
  namespace: app
data:
  kafka.crt: ...
  user.crt: ...
  ca.crt: ...
  notes.txt: ...
```

You'll get three series, one per matched key:
```
x509_cert_not_after{secret_namespace="app", secret_name="bundle", secret_key="kafka.crt", subject_CN="..."}
x509_cert_not_after{secret_namespace="app", secret_name="bundle", secret_key="user.crt", subject_CN="..."}
x509_cert_not_after{secret_namespace="app", secret_name="bundle", secret_key="ca.crt", subject_CN="..."}
```
