### ISSUE TITLE
[x509-certificate-exporter] prometheusServiceMonitor: coalesce.go:220: warning: cannot overwrite table with non table

### ISSUE THREAD

**Issue by r0bj** [enix/x509-certificate-exporter#43]
Relabelings config for ServiceMonitor and PodMonitor generates warning:
```
coalesce.go:220: warning: cannot overwrite table with non table for x509-certificate-exporter.prometheusServiceMonitor.relabelings (map[])
```

Example.
values.yaml:
```
prometheusServiceMonitor:
  relabelings:
  - targetLabel: job
    replacement: x509-certificate-exporter
```

Generate helm manifests:
```
$ helm template x509-certificate-exporter enix/x509-certificate-exporter -f values.yaml
coalesce.go:220: warning: cannot overwrite table with non table for x509-certificate-exporter.prometheusServiceMonitor.relabelings (map[])
[...]
```

What's interesting it generates valid ServiceMonitor:
```
---
# Source: x509-certificate-exporter/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: x509-certificate-exporter
  labels:
    helm.sh/chart: x509-certificate-exporter-1.20.0
    app.kubernetes.io/name: x509-certificate-exporter
    app.kubernetes.io/instance: x509-certificate-exporter
    app.kubernetes.io/version: "2.12.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: x509-certificate-exporter
      app.kubernetes.io/instance: x509-certificate-exporter
  endpoints:
  - port: metrics
    interval: 60s
    scrapeTimeout: 10s
    relabelings:
      - replacement: x509-certificate-exporter
        targetLabel: job
```

Also documentation for `prometheusServiceMonitor.relabelings` and `prometheusPodMonitor.relabelings` says that it's type object but it should be a list, after prometheus-operator API docs https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint:
```
 relabelings []*RelabelConfig
```
