### ISSUE TITLE
BREAKING CHANGE 3.19.0: a33e897b0e7b8a1bd71bfe68eb6e10e749a0c6d7

### ISSUE THREAD

**Issue by volker-raschek** [enix/x509-certificate-exporter#445]
The patch a33e897b0e7b8a1bd71bfe68eb6e10e749a0c6d7 introduced probes. The default scheme for all probes is now HTTP. This leads in environments, where the TLS features, introduced with ff9954126b5ecea0e550d013554c957e8b93f8aa to issues, because the application is listing on HTTPS, but the probe use HTTP to establish a connection.

Furthermore, the `scheme` can not be configured via the `values.yaml`. The only way to avoid this issue is currently to rollback environments to `v3.18.1`.

**Comment by npdgm** [comment]
Thanks a lot. Obviously we don't test for TLS, I'll see that we improve CI testing and have this scenario implemented.
Working on a fix...

**Comment by volker-raschek** [comment]
Hi, 
maybe with https://github.com/helm-unittest/helm-unittest

I use this plugin for my own helm charts: https://git.cryptic.systems/volker.raschek/prometheus-fail2ban-exporter-charts

  Volker

**Comment by npdgm** [comment]
A new release is out with a patch to allow configuration of `httpGet` parameters in healthcheck probes, such as `scheme`.
We could probably streamline the configuration of TLS that now requires about 6 values to be set but that will do for now.

Please try version 3.19.1 and override `scheme` in every section:
```yaml
prometheusServiceMonitor:
  scheme: https
  tlsConfig:
    [....]

secretsExporter:
  livenessProbe:
    httpGet:
      scheme: HTTPS
  readinessProbe:
    httpGet:
      scheme: HTTPS

hostPathsExporter:
  livenessProbe:
    httpGet:
      scheme: HTTPS
  readinessProbe:
    httpGet:
      scheme: HTTPS
  daemonSets:
    [....]
```
