### ISSUE TITLE
Allow extravolumes / extramounts

### ISSUE THREAD

**Issue by sebv004** [enix/x509-certificate-exporter#67]
Hi guys, I would like to thank you for this really cool exporter.
One of my application uses a cert stored in a K8S secret and I was guessing if it could be possible to mount this secret and add a watchfile to this one ?
Regards,
Seb.

**Comment by npdgm** [comment]
Hi Seb
Glad you like the project, and thanks for the kind words! :smiley: 

Providing options for `extraVolumes` and `extraMounts` is a great idea, and together with an `extraArgs` would offer fantastic flexibility for exotic use-cases.
So I'll work on adding this to our Chart, the more knobs the better :robot: 

Did you notice you could already tweak this default value? `secretTypes` specifies which type of Secret is watched, and what key to look for in onbect data.
```yaml
secretsExporter:
  secretTypes:
  - type: kubernetes.io/tls
    key: tls.crt
```
For example if you had a generic "Opaque" Secret with a certificate in key `mycert`, then this set of value would have the exporter find your certificate:
```yaml
secretsExporter:
  secretTypes:
  - type: kubernetes.io/tls
    key: tls.crt
  - type: Opaque
    key: mycert
```
Obviously that won't target specific Secrets by name and so lacks precision. But it has the advantage to find all such Secrets dynamically. It may be the best option when having a lot of such objects in your cluster. Much less if that was a few isolated cases.

I'll get back to you regarding Chart improvements.
Cheers
