### ISSUE TITLE
create rule only for the api

### ISSUE THREAD

**Issue by Meza1923** [enix/x509-certificate-exporter#95]
Hey 

I just installed the chart on my ocp cluster, and I want only to monitor the crt of the api.
Could someone help me achieve my goal?
Until now I set prometeusrule.create = false in order to create my own prometeusrules.
and I created with this configuration:

```
- alert: certificate
   rules: 
   - alert: certificate-expired
      annotations:
        description: Certificate of "{{ $labels.subject_CN }}" is about to end in {{ $value }} days
                {{if $labels.secret_name }}in Kubernetes secret "{{ $labels.secret_namespace
                }}/{{ $labels.secret_name }}"{{else}}
        summary: Certificate is about to expire
      expr: ((x509_cert_not_after - time()) / 86400) < 30
      for: 1h
      labels:
          severity: critical
```
