### ISSUE TITLE
Default values of resources  - proposal

### ISSUE THREAD

**Issue by hagaram** [enix/x509-certificate-exporter#96]
Hello, 
first of all, thank you for this exporter :).

**What do you think about the default resources value being unset e.g.
`resources: {}` ?**
With recommended values maybe commented out below.

Reason for that is.... if I for example don't want to set CPU limits

```
  resources:
    limits:
      memory: 150Mi
    requests:
      cpu: 20m
      memory: 20Mi
```

It gets overriden with default values from this chart and my CPU limits are set, even if I don't want them to.

I wanted to make it work like below, but at least on v. 1.25.5 of kubernetes, this won't pass the k8s validator.

```
  resources:
    limits:
      cpu: "0"
      memory: 150Mi
    requests:
      cpu: 20m
      memory: 20Mi
```

So I delete the cpu limit via kustomize, which would not be needed if resources are unset.

**Comment by npdgm** [comment]
Hi,

Glad you like the project, and thank you for asking this interesting question.

> What do you think about the default resources value being unset e.g. `resources: {}` ?

That would not be a sensible default, as our goal with values is to find a balance between best practices and maximum compatibility by default. I'm afraid both advocate for a fully set `resources`. That way the exporter runs at the "Guaranteed" QoS class, we do not take any risk in case of a bug, protect the api-server in some ways having limited CPU available to the client, and be compatible with admission controllers requiring `resources`.

But don't worry, unless you'd be using an ancient version of Helm 2, there is a solution with the `null` keyword. This will make Helm's 3-way strategic merge to understand you want to override the key with void.
Looking back at your example, you could be using:
```yaml
  resources:
    limits:
      cpu: null
      memory: 150Mi
    requests:
      cpu: 20m
      memory: 20Mi
```
Or to leave all other `resources` to the default and allow an upgrade:
```yaml
  resources:
    limits:
      cpu: null
```

Here is a demo:
```
❯ helm template enix/x509-certificate-exporter | yq 'select(.kind == "Deployment") | .spec.template.spec.containers[].resources'
limits:
  cpu: 200m
  memory: 150Mi
requests:
  cpu: 20m
  memory: 20Mi

❯ helm template enix/x509-certificate-exporter --set secretsExporter.resources.limits.cpu=null | yq 'select(.kind == "Deployment") | .spec.template.spec.containers[].resources'
limits:
  memory: 150Mi
requests:
  cpu: 20m
  memory: 20Mi
```

Is that a solution you can implement with your deployment?

Cheers
